__version__ = "7.0.0"
__release_date__ = "2026-05-01"
__description__ = "Warren Trading Bot — AI-powered trading bot"

CHANGELOG = {
    "7.0.0": [
        "_detect_anomalies(): 연속손실/섹터집중/장기보유/대형미실현손실 4가지 이상 감지",
        "_generate_daily_report(): 포트폴리오+성과+레짐+이상+오픈포지션+권고사항 종합 일일 리포트",
        "logs/journal/YYYY-MM-DD-ai_report.json 자동 저장 (일 1회)",
        "step_ai_ops() in run_master_loop.py: Step 2d, 일 1회 실행 (중복 방지)",
        "_send_ai_report_telegram(): 리포트 텔레그램 전송 (이상/권고 포함)",
        "run_master_loop.py v7.0: Step 1→2→2b→2c→2d→3 전체 파이프라인 완성",
        "거래 실행 절대 금지 — 분석/알림 전용",
        "tests/test_v70_ai_ops.py: 12개 단위 테스트 (2개 클래스)",
        "docs/WARREN_V7.0.md 신규 작성",
    ],
    "6.2.0": [
        "_generate_capital_allocation_proposal(): by_market 30d 성과 + 레짐 기반 KR/US/CRYPTO 자본 배분 % 제안",
        "제약: ±20%p 이내 조정, 합계 100%, PENDING 상태, INITIAL_CAPITAL 자동 수정 금지",
        "RISK_OFF → CRYPTO 점수 0.3배 축소 / TRENDING → US 점수 1.2배 가중",
        "step_capital_allocation() in run_master_loop.py: Step 2c로 자동 실행",
        "텔레그램: 자본 배분 제안 메시지 (현재→제안→변화 %p)",
        "tests/test_v62_capital_allocation.py: 12개 단위 테스트 (3개 클래스)",
        "docs/WARREN_V6.2.md 신규 작성",
    ],
    "6.1.0": [
        "_detect_market_regime() v6.1: SPY 200MA(0~2) + QQQ slope(0~1) + VIX(0~2) + breadth_pct(0~1) + BTC_dom(0~1) 5지표 합산",
        "가중 점수 레짐 판정: ≥5→TRENDING / 2~4→SIDEWAYS / ≤1→RISK_OFF + 하드트리거(SPY≤-2% OR VIX≥30)",
        "breadth_pct: US 유니버스 종목 중 50MA 위 비율 (0~1)",
        "btc_dominance: BTC/(BTC+ETH+SOL) 시가총액 추정 (0~1)",
        "_append_regime_history(): logs/regime_history.json 누적 저장 (최대 200개)",
        "tests/test_v61_market_regime.py: 14개 단위 테스트 (3개 클래스)",
        "docs/WARREN_V6.1.md 신규 작성",
    ],
    "6.0.0": [
        "_detect_market_regime(): SPY 200MA / QQQ 50MA 기울기 / VIX 기반 레짐 감지 (TRENDING/SIDEWAYS/RISK_OFF)",
        "ROTATION_STRATEGY: 레짐별 US/KR/CRYPTO 전략 우선순위 테이블 (참고용)",
        "_generate_rotation_proposal(): PENDING 제안 생성 (절대 자동 적용 금지)",
        "run_master_loop.py: step_regime_rotation() 추가 → strategy_proposals.json 저장",
        "텔레그램 알림: 레짐 표시(🟢/🟡/🔴) + 로테이션 제안 메시지 추가",
        "tests/test_v60_strategy_rotation.py: 18개 단위 테스트 (3개 클래스)",
        "docs/WARREN_V6.0.md 신규 작성",
    ],
    "5.3.0": [
        "_compute_performance_report(): 30일/90일/전체 윈도우 × ticker별/전략별 성과 분석",
        "metrics: trades/win_rate/profit_factor/expectancy_krw/avg_win/avg_loss/sharpe/max_drawdown_pct",
        "PERF_REPORT_FILE = logs/performance_report.json — run_once() 실행 시마다 자동 갱신",
        "run_once() 성과 요약 2줄 출력: [성과-전체] PF/Exp/Sharpe/MDD + [성과-30d] 거래수/WR/PF/Exp",
        "run_once() 버전 표시 v5.1 → v5.3",
        "tests/test_v53_performance.py: 14개 단위 테스트 (4개 클래스)",
        "docs/WARREN_V5.3.md 신규 작성",
    ],
    "5.2.0": [
        "_get_atr(): yfinance 일봉 60d 기반 ATR(14) 계산, ATR% 반환 (None if 데이터 부족)",
        "calc_risk_based_position_size(): dict 반환으로 변경 (sl_based/atr_based/recommended/risk_krw/sl_pct/atr_pct_used)",
        "open_positions() 진입 로그에 고정/SL기반/ATR기반 3-way 비교 출력 (참고용)",
        "실전 주문은 여전히 POSITION_SIZE 고정값 사용 (ATR 적용은 v5.3에서 결정)",
        "tests/test_v52_atr_sizing.py: 14개 단위 테스트 (TestCalcRiskBasedPositionSizeV52/TestGetAtr/TestSizingComparison)",
        "docs/WARREN_V5.2.md 신규 작성",
    ],
    "5.1.0": [
        "헤더 수정: 27종목 → 30종목 (KR16+US10+CRYPTO4) 정합성 수정",
        "Weekly Loss Limit 구현: 이번 주 월요일 이후 pnl_krw 집계, -5% 차단",
        "Peak Equity 기반 MDD: current/peak_equity 비율로 진짜 MDD 계산",
        "미실현손익 포함 Daily Circuit Breaker: 실현+미실현 합산 -1.5% 체크",
        "현재가 2분 캐시(_PRICE_CACHE): 중복 API 호출 방지, 미실현손익 계산 가속",
        "calc_risk_based_position_size(): ATR/SL 기반 권장 포지션 사이즈 계산 함수 추가",
        "포트폴리오 메트릭 확장: 전체/시장별/전략별 trades/WR/PF/Expectancy",
        "settings.py 단일화: MAX_SECTOR_POSITIONS/RISK_PER_TRADE_PCT 추가, 하드코딩 제거",
        "진입 로그에 '권장ATR 사이즈' 병기 (참고용)",
        "run_master_loop.py 텔레그램에 Manual approval required 추가",
        "docs/WARREN_V5.1.md 신규 작성",
    ],
    "5.0.0": [
        "Circuit Breaker 강화: 일일 손실 -1.5% / MDD -10% 서킷브레이커 자동 차단",
        "섹터 집중도 관리: 동일 섹터 최대 2포지션 (KR/US 적용, CRYPTO 제외)",
        "포트폴리오 메트릭 자동 계산: Sharpe Ratio / Profit Factor / Expectancy",
        "config/settings.py 리스크 한도 강화: DAILY_LOSS_LIMIT -1.5% / MDD_LIMIT -10%",
        "SECTOR_MAP 도입: KR 16종목 / US 10종목 섹터 분류",
        "WARREN_V5.0.md 문서 작성",
        "대시보드 시스템 문서 페이지 추가",
    ],
    "4.6.0": [
        "KIS API 현재가 1순위 연결 (KR 종목)",
        "전략 레지스트리 패턴 도입 (_KR_STRATEGY_FN / _US_STRATEGY_FN)",
        "KR 전 종목 전략 배정 완성 (16종목, BB_SWING/MOMENTUM/MACD/SUPERTREND/GAPGO)",
        "TP 연장 전략 구현 (TP1→TP2→TP3, 6조건 체크, 트레일링 SL)",
        "15m 보조지표 3종 필터 (EMA정렬+CHoCH+SL정밀화)",
        "화이트리스트 이중 방어선 (scan_all + open_positions 양쪽 검증)",
        "068270(셀트리온)/000270(기아) 유니버스 외 종목 영구 차단",
        "BB반등 조건 강화: RSI<60, BB1σ이하 (V4_RELAXED 원복)",
        "MIN_ENTRY_QUALITY 4점으로 원복 (케이스 30건+ 달성)",
        "POSITION_SIZE 재조정: KR 500만/US 1000만/CRYPTO 500만",
        "config/assets.py V4.6 동기화 (PLTR/SOXX 퇴출, 전략 배정 추가)",
        "저널 자동화 3세션 (07:00/17:00/21:00), 대시보드 자동갱신",
        "run_journal.py 한글 깨짐 수정, afternoon_review 연동",
        "win_rate_pct 자동 갱신 (_save_portfolio), 중복 거래 방지 강화",
    ],
    "4.5.0": [
        "V4.5 초기 버전: 페이퍼 트레이딩 포트폴리오 통합",
        "FVG+OB 스캐너 KR 스윙 모드 전환",
        "5m 확인 캔들, 주봉 HTF 필터 추가",
    ],
}
